// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import MapController from "./map_controller"
import FiltersController from "./filters_controller"
import FilterableListController from "./filterable_list_controller"
import PopoverController from "./popover_controller"

application.register("map", MapController)
application.register("filters", FiltersController)
application.register("filterableList", FilterableListController)
application.register("popover", PopoverController)
